// <auto-generated />
using System;
using BerberSimulasyonu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BerberSimulasyonu.Migrations
{
    [DbContext(typeof(BerberDbContext))]
    [Migration("20260504115425_AddApplicationSystem")]
    partial class AddApplicationSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BerberSimulasyonu.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DiscountPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VisitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("DefaultWorkEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("DefaultWorkStart")
                        .HasColumnType("time");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("WorkEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WorkStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.EmployeeApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<decimal>("DesiredHourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DesiredPosition")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Experience")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QuizAnswers")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("QuizScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.ToTable("EmployeeApplications");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Explanation")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Saç Kesimi",
                            CorrectOption = "A",
                            CreatedDate = new DateTime(2026, 5, 4, 14, 54, 24, 293, DateTimeKind.Local).AddTicks(7084),
                            Difficulty = 1,
                            Explanation = "Klasik erkek saç kesiminde genellikle 3-4 numara makine başlığı kullanılır.",
                            IsActive = true,
                            OptionA = "3-4 numara",
                            OptionB = "1-2 numara",
                            OptionC = "6-8 numara",
                            OptionD = "9-12 numara",
                            Question = "Makine ile saç kesiminde genellikle hangi numara makine başlığı kullanılır?"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sakal",
                            CorrectOption = "A",
                            CreatedDate = new DateTime(2026, 5, 4, 14, 54, 24, 293, DateTimeKind.Local).AddTicks(7104),
                            Difficulty = 1,
                            Explanation = "Sıcak havlu uygulaması sakalları yumuşatır ve cildi tıraşa hazırlar.",
                            IsActive = true,
                            OptionA = "Sıcak havlu uygulaması",
                            OptionB = "Soğuk su ile yıkama",
                            OptionC = "Kuru tıraş",
                            OptionD = "Jilet direkt uygulanır",
                            Question = "Sakal traşı öncesi cildi hazırlamak için en iyi yöntem nedir?"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Hijyen",
                            CorrectOption = "A",
                            CreatedDate = new DateTime(2026, 5, 4, 14, 54, 24, 293, DateTimeKind.Local).AddTicks(7107),
                            Difficulty = 1,
                            Explanation = "Hijyen için her müşteri için temiz ve steril malzeme kullanmak esastır.",
                            IsActive = true,
                            OptionA = "Her müşteri için temiz malzeme kullanmak",
                            OptionB = "Hızlı çalışmak",
                            OptionC = "Pahalı ürünler kullanmak",
                            OptionD = "Dükkanı süslemek",
                            Question = "Berber dükkanında hijyen için en önemli kural nedir?"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Saç Boyama",
                            CorrectOption = "A",
                            CreatedDate = new DateTime(2026, 5, 4, 14, 54, 24, 293, DateTimeKind.Local).AddTicks(7110),
                            Difficulty = 2,
                            Explanation = "Saç boyası genellikle 30-45 dakika etkisini gösterir.",
                            IsActive = true,
                            OptionA = "30-45 dakika",
                            OptionB = "5-10 dakika",
                            OptionC = "2-3 saat",
                            OptionD = "Hemen durulayabilir",
                            Question = "Saç boyama işlemi sonrasında ne kadar beklemek gerekir?"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sakal",
                            CorrectOption = "A",
                            CreatedDate = new DateTime(2026, 5, 4, 14, 54, 24, 293, DateTimeKind.Local).AddTicks(7112),
                            Difficulty = 2,
                            Explanation = "Jilet ile tıraşta genellikle 30 derecelik açı kullanılır.",
                            IsActive = true,
                            OptionA = "30 derece",
                            OptionB = "90 derece",
                            OptionC = "45 derece",
                            OptionD = "15 derece",
                            Question = "Jilet ile tıraşta en sık kullanılan açı nedir?"
                        });
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Saç",
                            Description = "Makine veya makasla standart saç kesimi",
                            IsActive = true,
                            Name = "Klasik Saç Kesimi",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Saç",
                            Description = "Trend ve modern saç kesim teknikleri",
                            IsActive = true,
                            Name = "Modern Saç Kesimi",
                            Price = 150m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Saç",
                            Description = "Tek renk tam saç boyama hizmeti",
                            IsActive = true,
                            Name = "Saç Boyama",
                            Price = 400m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sakal",
                            Description = "Sakal şekillendirme ve tıraş",
                            IsActive = true,
                            Name = "Klasik Sakal Kesimi",
                            Price = 80m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sakal",
                            Description = "Jilet ile profesyonel sakal traşı",
                            IsActive = true,
                            Name = "Sakal Traşı",
                            Price = 60m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Sakal",
                            Description = "Sakal ve bıyık boyama hizmeti",
                            IsActive = true,
                            Name = "Sakal Boyama",
                            Price = 150m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Saç",
                            Description = "Saç kesimi + sakal kesimi kombin paketi",
                            IsActive = true,
                            Name = "Saç ve Sakal Paket",
                            Price = 160m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Sakal",
                            Description = "Rahatlatıcı ve yenileyici yüz masajı",
                            IsActive = true,
                            Name = "Yüz Masajı",
                            Price = 100m
                        });
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Appointment", b =>
                {
                    b.HasOne("BerberSimulasyonu.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BerberSimulasyonu.Models.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BerberSimulasyonu.Models.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.EmployeeApplication", b =>
                {
                    b.HasOne("BerberSimulasyonu.Models.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("BerberSimulasyonu.Models.EmployeeApplication", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Employee", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BerberSimulasyonu.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
